apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: portfolio-v1
  name: portfolio-v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portfolio-v1
  template:
    metadata:
      labels:
        app: portfolio-v1
    spec:
      containers:
      - image: shyamr30/portfolio-v1:latest
        name: portfolio-v1
        ports:
        - containerPort: 3000
          name: portfolio-v1
