apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: portfolio-v1
  name: portfolio-v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portfolio-v1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: portfolio-v1
    spec:
      containers:
      - image: shyamr30/portfolio-v1:latest
        name: portfolio-v1
        ports:
        - containerPort: 3000
          name: portfolio-v1
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "300m"
        envFrom:
        - configMapRef:
            name: portfolio-config
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
