apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: portfolio-v1
  name: portfolio-v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portfolio-v1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: portfolio-v1
    spec:
      containers:
      - image: shyamr30/portfolio-v1:latest
        name: portfolio-v1
        ports:
        - containerPort: 3000
          name: portfolio-v1
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "300m"
        env:
        - name: PORT
          value: "3000"
        - name: NODE_ENV
          value: "production"
        - name: REACT_APP_API_URL
          value: "https://api.example.com"
        - name: PUBLIC_URL
          value: "/"
        - name: GENERATE_SOURCEMAP
          value: "false"
        startupProbe:
          httpGet:
            path: /health.html
            port: 3000
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 30
        livenessProbe:
          httpGet:
            path: /health.html
            port: 3000
          initialDelaySeconds: 120
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 6
        readinessProbe:
          httpGet:
            path: /health.html
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
