apiVersion: v1
kind: Service
metadata:
  labels:
    app: portfolio-v1
  name: portfolio-v1
spec:
  type: NodePort
  ports:
    - name: "portfolio-v1-service"
      port: 3000
      targetPort: 3000
      nodePort: 31003
  selector:
    app: portfolio-v1
